/**
 * RBAC 純粋ヘルパー（client-safe）
 *
 * `hasPermission` / `ROLE_PERMISSIONS` を server-only 依存から分離した SSoT。
 * shared/domain 配下の admin 系 query helper（admin-search / audit-recents 等）から
 * 直接参照できるよう shared/lib に配置。
 *
 * server-only 周辺（`userHasPermission` / `userHasResourceAccess` 等の
 * Better Auth セッション/Prisma 連携部分）は admin layer に残す。
 */

import type { Role } from "@/shared/lib/validations/enums/prisma-types";
import type { Resource, Action } from "@/shared/lib/admin-resources";

/** 権限キー（resource:action） */
export type PermissionKey = `${Resource}:${Action}`;

/** ロール別権限定義 */
export type RolePermissions = Record<Role, PermissionKey[]>;

/**
 * ロール別の権限定義
 *
 * SUPER_ADMIN: 全権限
 * ADMIN: コンテンツ管理全般
 * EDITOR: 割り当て page 編集のみ（page / media upload / blockTemplate read /
 *   notification read）。post / news / faq / event / コンテンツ系は ADMIN+ 専管。
 *   `userPageAssignment` で page-level access を gate する設計のため、独立 resource
 *   への編集権限は与えない（`userHasResourceAccess` は page UUID 専用判定）
 * VIEWER: 閲覧のみ
 * USER / CUSTOMER: 管理機能なし
 */
export const ROLE_PERMISSIONS: RolePermissions = {
  SUPER_ADMIN: [
    "space:create",
    "space:read",
    "space:update",
    "space:delete",
    "space:publish",
    "location:create",
    "location:read",
    "location:update",
    "location:delete",
    "location:publish",
    "spaceCategory:create",
    "spaceCategory:read",
    "spaceCategory:update",
    "spaceCategory:delete",
    "spaceCategory:manage",
    "reservation:create",
    "reservation:read",
    "reservation:update",
    "reservation:delete",
    "reservation:manage",
    "customer:create",
    "customer:read",
    "customer:update",
    "customer:delete",
    "customer:manage",
    "inquiry:read",
    "inquiry:update",
    "inquiry:delete",
    "inquiry:manage",
    "post:create",
    "post:read",
    "post:update",
    "post:delete",
    "post:publish",
    "news:create",
    "news:read",
    "news:update",
    "news:delete",
    "news:publish",
    "page:create",
    "page:read",
    "page:update",
    "page:delete",
    "page:publish",
    "faq:create",
    "faq:read",
    "faq:update",
    "faq:delete",
    "faq:manage",
    "terms:create",
    "terms:read",
    "terms:update",
    "terms:delete",
    "terms:publish",
    "settings:read",
    "settings:update",
    "settings:manage",
    "user:create",
    "user:read",
    "user:update",
    "user:delete",
    "user:manage",
    "auditLog:read",
    "auditLog:manage",
    "navigation:create",
    "navigation:read",
    "navigation:update",
    "navigation:delete",
    "navigation:manage",
    "announcementBar:create",
    "announcementBar:read",
    "announcementBar:update",
    "announcementBar:delete",
    "announcementBar:manage",
    "media:create",
    "media:read",
    "media:update",
    "media:delete",
    "media:manage",
    "coupon:create",
    "coupon:read",
    "coupon:update",
    "coupon:delete",
    "coupon:manage",
    "blockTemplate:create",
    "blockTemplate:read",
    "blockTemplate:delete",
    "blockTemplate:manage",
    "review:read",
    "review:update",
    "review:delete",
    "event:create",
    "event:read",
    "event:update",
    "event:delete",
    "event:publish",
    "notification:read",
    "notification:update",
    "notification:delete",
  ],
  ADMIN: [
    "space:create",
    "space:read",
    "space:update",
    "space:delete",
    "space:publish",
    "location:create",
    "location:read",
    "location:update",
    "location:delete",
    "location:publish",
    "spaceCategory:create",
    "spaceCategory:read",
    "spaceCategory:update",
    "spaceCategory:delete",
    "spaceCategory:manage",
    "reservation:create",
    "reservation:read",
    "reservation:update",
    "reservation:delete",
    "reservation:manage",
    "customer:create",
    "customer:read",
    "customer:update",
    "customer:delete",
    "customer:manage",
    "inquiry:read",
    "inquiry:update",
    "inquiry:delete",
    "inquiry:manage",
    "post:create",
    "post:read",
    "post:update",
    "post:delete",
    "post:publish",
    "news:create",
    "news:read",
    "news:update",
    "news:delete",
    "news:publish",
    "page:create",
    "page:read",
    "page:update",
    "page:delete",
    "page:publish",
    "faq:create",
    "faq:read",
    "faq:update",
    "faq:delete",
    "faq:manage",
    "terms:create",
    "terms:read",
    "terms:update",
    "terms:delete",
    "terms:publish",
    "settings:read",
    "settings:update",
    // ユーザー管理（階層制御あり — admin-roles.ts INVITABLE_BY で EDITOR/VIEWER のみ操作可）
    // `user:manage`（ロール変更等の特権操作）は SUPER_ADMIN 専用で温存
    "user:create",
    "user:read",
    "user:update",
    "user:delete",
    "navigation:create",
    "navigation:read",
    "navigation:update",
    "navigation:delete",
    "navigation:manage",
    "announcementBar:create",
    "announcementBar:read",
    "announcementBar:update",
    "announcementBar:delete",
    "announcementBar:manage",
    "media:create",
    "media:read",
    "media:update",
    "media:delete",
    "media:manage",
    "coupon:create",
    "coupon:read",
    "coupon:update",
    "coupon:delete",
    "coupon:manage",
    "blockTemplate:create",
    "blockTemplate:read",
    "blockTemplate:delete",
    "blockTemplate:manage",
    "review:read",
    "review:update",
    "review:delete",
    "event:create",
    "event:read",
    "event:update",
    "event:delete",
    "event:publish",
    "notification:read",
    "notification:update",
    "notification:delete",
  ],
  EDITOR: [
    "page:read",
    "page:update",
    "media:create",
    "media:read",
    "media:update",
    "blockTemplate:read",
    "notification:read",
  ],
  VIEWER: [
    "space:read",
    "location:read",
    "spaceCategory:read",
    "reservation:read",
    "customer:read",
    "inquiry:read",
    "post:read",
    "news:read",
    "page:read",
    "faq:read",
    "terms:read",
    "settings:read",
    "navigation:read",
    "announcementBar:read",
    "media:read",
    "review:read",
    "event:read",
    "notification:read",
  ],
  USER: [],
  CUSTOMER: [],
};

/**
 * ロールが権限を持つかチェック（同期、純粋関数）
 */
export function hasPermission(
  role: Role,
  resource: Resource,
  action: Action,
): boolean {
  const permissions = ROLE_PERMISSIONS[role];
  const key: PermissionKey = `${resource}:${action}`;
  return permissions.includes(key);
}
