/**
 * Layout insert items — レイアウト骨格 + コンテンツパターン
 *
 * カラム・グループ・コールアウト・プルクォート・折りたたみ・ステップ・タブ・カバー等のレイアウト骨格と、
 * タイムライン・料金表・テスティモニアル・設備リスト等の複合コンテンツパターンを含む。
 */

import {
  IconAlertCircle,
  IconBox,
  IconChevronsDown,
  IconClock,
  IconColumns3,
  IconLayoutBottombar,
  IconLayoutNavbar,
  IconMessageChatbot,
  IconQuote,
  IconRowInsertBottom,
  IconShoe,
  IconTable,
} from "@tabler/icons-react";
import { INSERT_CAPTION_BOX_COMMAND } from "../../plugins/CaptionBoxPlugin";
import { INSERT_COLLAPSIBLE_COMMAND } from "../../plugins/CollapsiblePlugin";
import { INSERT_GROUP_COMMAND } from "../../plugins/GroupPlugin";
import type { InsertItem } from "./types";

export const LAYOUT_INSERT_ITEMS: readonly InsertItem[] = [
  // ========== レイアウト骨格 ==========
  {
    id: "layout",
    type: "dialog",
    label: "カラム",
    icon: IconColumns3,
    keywords: ["column", "layout", "grid", "karamu", "2column", "3column"],
    category: "layout",
    showInToolbar: true,
    showInPicker: true,
    dialogId: "layout",
  },
  {
    id: "group",
    type: "command",
    label: "グループ",
    icon: IconBox,
    keywords: [
      "group",
      "box",
      "container",
      "border",
      "background",
      "guruupu",
      "bokkusu",
      "waku",
    ],
    category: "layout",
    showInToolbar: true,
    showInPicker: true,
    dispatch: (editor) =>
      editor.dispatchCommand(INSERT_GROUP_COMMAND, {
        groupStyle: "solid-border",
      }),
  },
  {
    id: "callout",
    type: "dialog",
    label: "コールアウト",
    icon: IconAlertCircle,
    keywords: ["callout", "alert", "note", "chuui", "info", "warning"],
    category: "layout",
    showInToolbar: true,
    showInPicker: true,
    dialogId: "callout",
  },
  {
    id: "pullQuote",
    type: "dialog",
    label: "プルクォート",
    icon: IconQuote,
    keywords: ["pullquote", "quote", "inyou", "blockquote", "highlight"],
    category: "layout",
    showInToolbar: true,
    showInPicker: true,
    dialogId: "pullQuote",
  },
  {
    id: "collapsible",
    type: "command",
    label: "折りたたみ",
    icon: IconChevronsDown,
    keywords: [
      "collapsible",
      "accordion",
      "faq",
      "oritakamu",
      "toggle",
      "details",
    ],
    category: "layout",
    showInToolbar: true,
    showInPicker: true,
    dispatch: (editor) =>
      editor.dispatchCommand(INSERT_COLLAPSIBLE_COMMAND, undefined),
  },
  {
    id: "caption-box",
    type: "command",
    label: "キャプションボックス",
    icon: IconLayoutBottombar,
    keywords: [
      "caption",
      "box",
      "キャプション",
      "ボックス",
      "highlight",
      "titled",
    ],
    category: "layout",
    showInToolbar: true,
    showInPicker: true,
    dispatch: (editor) =>
      editor.dispatchCommand(INSERT_CAPTION_BOX_COMMAND, undefined),
  },
  {
    id: "steps",
    type: "dialog",
    label: "ステップ",
    icon: IconShoe,
    keywords: ["steps", "howto", "guide", "junban", "tejun", "process"],
    category: "layout",
    showInToolbar: true,
    showInPicker: true,
    dialogId: "steps",
  },
  {
    id: "tabs",
    type: "dialog",
    label: "タブ",
    icon: IconLayoutNavbar,
    keywords: ["tabs", "tabu", "switch", "panel", "toggle"],
    category: "layout",
    showInToolbar: true,
    showInPicker: true,
    dialogId: "tabs",
  },
  {
    id: "cover",
    type: "dialog",
    label: "カバー",
    icon: IconLayoutNavbar,
    keywords: [
      "cover",
      "hero",
      "background",
      "image",
      "背景",
      "カバー",
      "ヒーロー",
    ],
    category: "layout",
    showInToolbar: true,
    showInPicker: true,
    dialogId: "cover",
  },

  // ========== コンテンツパターン ==========
  {
    id: "timeline",
    type: "dialog",
    label: "タイムライン",
    icon: IconClock,
    keywords: [
      "timeline",
      "タイムライン",
      "history",
      "歴史",
      "chronology",
      "年表",
    ],
    category: "patterns",
    showInToolbar: false,
    showInPicker: true,
    dialogId: "timeline",
  },
  {
    id: "pricingTable",
    type: "dialog",
    label: "料金比較表",
    icon: IconTable,
    keywords: ["pricing", "price", "plan", "料金", "比較", "table", "プラン"],
    category: "patterns",
    showInToolbar: false,
    showInPicker: true,
    dialogId: "pricingTable",
  },
  {
    id: "testimonial",
    type: "dialog",
    label: "口コミ・テスティモニアル",
    icon: IconMessageChatbot,
    keywords: [
      "testimonial",
      "review",
      "口コミ",
      "レビュー",
      "評価",
      "customer",
    ],
    category: "patterns",
    showInToolbar: false,
    showInPicker: true,
    dialogId: "testimonial",
  },
  {
    id: "feature-icon-list",
    type: "dialog",
    label: "設備・特徴リスト",
    icon: IconRowInsertBottom,
    keywords: [
      "feature",
      "icon",
      "list",
      "amenity",
      "設備",
      "特徴",
      "アイコン",
      "リスト",
    ],
    category: "patterns",
    showInToolbar: false,
    showInPicker: true,
    dialogId: "feature-icon-list",
  },
];
