-- squawk-ignore-file renaming-column
--
-- CMS（ページ・投稿・お知らせ・セクション・FAQ・ナビ・メディア・編集コメント）の
-- 物理列名を snake_case へ寄せる。
--
-- 免除の根拠・自動生成を使わない理由は 20260804110000（認証と顧客）と同じ。
-- 対象表の手書き CHECK 2 本は名前が既に snake_case なので改名は要らない。

BEGIN;

-- 1. 列
ALTER TABLE pages RENAME COLUMN "metaDescription" TO meta_description;
ALTER TABLE pages RENAME COLUMN "metaKeywords" TO meta_keywords;
ALTER TABLE pages RENAME COLUMN "ogpTitle" TO ogp_title;
ALTER TABLE pages RENAME COLUMN "ogpDescription" TO ogp_description;
ALTER TABLE pages RENAME COLUMN "ogpImageUrl" TO ogp_image_url;
ALTER TABLE pages RENAME COLUMN "isPublished" TO is_published;
ALTER TABLE pages RENAME COLUMN "publishedAt" TO published_at;
ALTER TABLE pages RENAME COLUMN "isActive" TO is_active;
ALTER TABLE pages RENAME COLUMN "isSystemPage" TO is_system_page;
ALTER TABLE pages RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE pages RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE posts RENAME COLUMN "content" TO content_html;
ALTER TABLE posts RENAME COLUMN "contentJson" TO content_json;
ALTER TABLE posts RENAME COLUMN "thumbnailUrl" TO thumbnail_url;
ALTER TABLE posts RENAME COLUMN "ogpImageUrl" TO ogp_image_url;
ALTER TABLE posts RENAME COLUMN "categoryId" TO category_id;
ALTER TABLE posts RENAME COLUMN "metaDescription" TO meta_description;
ALTER TABLE posts RENAME COLUMN "metaKeywords" TO meta_keywords;
ALTER TABLE posts RENAME COLUMN "ogpTitle" TO ogp_title;
ALTER TABLE posts RENAME COLUMN "ogpDescription" TO ogp_description;
ALTER TABLE posts RENAME COLUMN "publishedAt" TO published_at;
ALTER TABLE posts RENAME COLUMN "viewCount" TO view_count;
ALTER TABLE posts RENAME COLUMN "authorId" TO author_id;
ALTER TABLE posts RENAME COLUMN "contentWidth" TO content_width;
ALTER TABLE posts RENAME COLUMN "contentWidthCustom" TO content_width_custom;
ALTER TABLE posts RENAME COLUMN "deletedAt" TO deleted_at;
ALTER TABLE posts RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE posts RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE post_categories RENAME COLUMN "metaTitle" TO meta_title;
ALTER TABLE post_categories RENAME COLUMN "metaDescription" TO meta_description;
ALTER TABLE post_categories RENAME COLUMN "ogpImageUrl" TO ogp_image_url;
ALTER TABLE post_categories RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE post_categories RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE post_tags RENAME COLUMN "metaTitle" TO meta_title;
ALTER TABLE post_tags RENAME COLUMN "metaDescription" TO meta_description;
ALTER TABLE post_tags RENAME COLUMN "ogpImageUrl" TO ogp_image_url;
ALTER TABLE post_tags RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE post_tags RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE post_tag_on_posts RENAME COLUMN "postId" TO post_id;
ALTER TABLE post_tag_on_posts RENAME COLUMN "tagId" TO tag_id;
ALTER TABLE news RENAME COLUMN "content" TO content_html;
ALTER TABLE news RENAME COLUMN "contentJson" TO content_json;
ALTER TABLE news RENAME COLUMN "isPublished" TO is_published;
ALTER TABLE news RENAME COLUMN "publishedAt" TO published_at;
ALTER TABLE news RENAME COLUMN "contentWidth" TO content_width;
ALTER TABLE news RENAME COLUMN "contentWidthCustom" TO content_width_custom;
ALTER TABLE news RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE news RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE news RENAME COLUMN "metaDescription" TO meta_description;
ALTER TABLE news RENAME COLUMN "metaKeywords" TO meta_keywords;
ALTER TABLE news RENAME COLUMN "ogpTitle" TO ogp_title;
ALTER TABLE news RENAME COLUMN "ogpDescription" TO ogp_description;
ALTER TABLE news RENAME COLUMN "ogpImageUrl" TO ogp_image_url;
ALTER TABLE sections RENAME COLUMN "pageId" TO page_id;
ALTER TABLE sections RENAME COLUMN "isActive" TO is_active;
ALTER TABLE sections RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE sections RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE media RENAME COLUMN "storagePath" TO storage_path;
ALTER TABLE media RENAME COLUMN "mimeType" TO mime_type;
ALTER TABLE media RENAME COLUMN "uploadedBy" TO uploaded_by;
ALTER TABLE media RENAME COLUMN "isActive" TO is_active;
ALTER TABLE media RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE media RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE faq_categories RENAME COLUMN "isActive" TO is_active;
ALTER TABLE faq_categories RENAME COLUMN "deletedAt" TO deleted_at;
ALTER TABLE faq_categories RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE faq_categories RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE faq_items RENAME COLUMN "categoryId" TO category_id;
ALTER TABLE faq_items RENAME COLUMN "isPublished" TO is_published;
ALTER TABLE faq_items RENAME COLUMN "publishedAt" TO published_at;
ALTER TABLE faq_items RENAME COLUMN "deletedAt" TO deleted_at;
ALTER TABLE faq_items RENAME COLUMN "viewCount" TO view_count;
ALTER TABLE faq_items RENAME COLUMN "lastViewedAt" TO last_viewed_at;
ALTER TABLE faq_items RENAME COLUMN "helpfulCount" TO helpful_count;
ALTER TABLE faq_items RENAME COLUMN "notHelpfulCount" TO not_helpful_count;
ALTER TABLE faq_items RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE faq_items RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE navigation_items RENAME COLUMN "parentId" TO parent_id;
ALTER TABLE navigation_items RENAME COLUMN "isExternal" TO is_external;
ALTER TABLE navigation_items RENAME COLUMN "isActive" TO is_active;
ALTER TABLE navigation_items RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE navigation_items RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE social_links RENAME COLUMN "isActive" TO is_active;
ALTER TABLE social_links RENAME COLUMN "showOnDesktop" TO show_on_desktop;
ALTER TABLE social_links RENAME COLUMN "showOnMobile" TO show_on_mobile;
ALTER TABLE social_links RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE social_links RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE announcement_bars RENAME COLUMN "linkUrl" TO link_url;
ALTER TABLE announcement_bars RENAME COLUMN "linkText" TO link_text;
ALTER TABLE announcement_bars RENAME COLUMN "bgColor" TO bg_color;
ALTER TABLE announcement_bars RENAME COLUMN "textColor" TO text_color;
ALTER TABLE announcement_bars RENAME COLUMN "isActive" TO is_active;
ALTER TABLE announcement_bars RENAME COLUMN "displayOrder" TO display_order;
ALTER TABLE announcement_bars RENAME COLUMN "startAt" TO start_at;
ALTER TABLE announcement_bars RENAME COLUMN "endAt" TO end_at;
ALTER TABLE announcement_bars RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE announcement_bars RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE instagram_posts RENAME COLUMN "postId" TO post_id;
ALTER TABLE instagram_posts RENAME COLUMN "postUrl" TO post_url;
ALTER TABLE instagram_posts RENAME COLUMN "mediaUrl" TO media_url;
ALTER TABLE instagram_posts RENAME COLUMN "thumbnailUrl" TO thumbnail_url;
ALTER TABLE instagram_posts RENAME COLUMN "mediaType" TO media_type;
ALTER TABLE instagram_posts RENAME COLUMN "sortOrder" TO sort_order;
ALTER TABLE instagram_posts RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE instagram_posts RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE editor_comments RENAME COLUMN "threadId" TO thread_id;
ALTER TABLE editor_comments RENAME COLUMN "isDeleted" TO is_deleted;
ALTER TABLE editor_comments RENAME COLUMN "deletedAt" TO deleted_at;
ALTER TABLE editor_comments RENAME COLUMN "deletedBy" TO deleted_by;
ALTER TABLE editor_comments RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE editor_comments RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE editor_comments RENAME COLUMN "createdBy" TO created_by;
ALTER TABLE editor_comment_threads RENAME COLUMN "markId" TO mark_id;
ALTER TABLE editor_comment_threads RENAME COLUMN "contentType" TO content_type;
ALTER TABLE editor_comment_threads RENAME COLUMN "contentId" TO content_id;
ALTER TABLE editor_comment_threads RENAME COLUMN "quotedText" TO quoted_text;
ALTER TABLE editor_comment_threads RENAME COLUMN "resolvedAt" TO resolved_at;
ALTER TABLE editor_comment_threads RENAME COLUMN "resolvedBy" TO resolved_by;
ALTER TABLE editor_comment_threads RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE editor_comment_threads RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE editor_comment_threads RENAME COLUMN "createdBy" TO created_by;

-- 2. Prisma 管理オブジェクト（FK / index）
ALTER TABLE "editor_comment_threads" RENAME CONSTRAINT "editor_comment_threads_createdBy_fkey" TO "editor_comment_threads_created_by_fkey";
ALTER TABLE "editor_comment_threads" RENAME CONSTRAINT "editor_comment_threads_resolvedBy_fkey" TO "editor_comment_threads_resolved_by_fkey";
ALTER TABLE "editor_comments" RENAME CONSTRAINT "editor_comments_createdBy_fkey" TO "editor_comments_created_by_fkey";
ALTER TABLE "editor_comments" RENAME CONSTRAINT "editor_comments_deletedBy_fkey" TO "editor_comments_deleted_by_fkey";
ALTER TABLE "editor_comments" RENAME CONSTRAINT "editor_comments_threadId_fkey" TO "editor_comments_thread_id_fkey";
ALTER TABLE "faq_items" RENAME CONSTRAINT "faq_items_categoryId_fkey" TO "faq_items_category_id_fkey";
ALTER TABLE "media" RENAME CONSTRAINT "media_uploadedBy_fkey" TO "media_uploaded_by_fkey";
ALTER TABLE "navigation_items" RENAME CONSTRAINT "navigation_items_parentId_fkey" TO "navigation_items_parent_id_fkey";
ALTER TABLE "post_tag_on_posts" RENAME CONSTRAINT "post_tag_on_posts_postId_fkey" TO "post_tag_on_posts_post_id_fkey";
ALTER TABLE "post_tag_on_posts" RENAME CONSTRAINT "post_tag_on_posts_tagId_fkey" TO "post_tag_on_posts_tag_id_fkey";
ALTER TABLE "posts" RENAME CONSTRAINT "posts_authorId_fkey" TO "posts_author_id_fkey";
ALTER TABLE "posts" RENAME CONSTRAINT "posts_categoryId_fkey" TO "posts_category_id_fkey";
ALTER TABLE "sections" RENAME CONSTRAINT "sections_pageId_fkey" TO "sections_page_id_fkey";
ALTER INDEX "announcement_bars_isActive_displayOrder_idx" RENAME TO "announcement_bars_is_active_display_order_idx";
ALTER INDEX "announcement_bars_startAt_endAt_idx" RENAME TO "announcement_bars_start_at_end_at_idx";
ALTER INDEX "editor_comment_threads_contentType_contentId_status_idx" RENAME TO "editor_comment_threads_content_type_content_id_status_idx";
ALTER INDEX "editor_comment_threads_createdBy_idx" RENAME TO "editor_comment_threads_created_by_idx";
ALTER INDEX "editor_comment_threads_markId_contentType_contentId_key" RENAME TO "editor_comment_threads_mark_id_content_type_content_id_key";
ALTER INDEX "editor_comment_threads_status_createdAt_idx" RENAME TO "editor_comment_threads_status_created_at_idx";
ALTER INDEX "editor_comments_createdBy_idx" RENAME TO "editor_comments_created_by_idx";
ALTER INDEX "editor_comments_isDeleted_idx" RENAME TO "editor_comments_is_deleted_idx";
ALTER INDEX "editor_comments_threadId_createdAt_idx" RENAME TO "editor_comments_thread_id_created_at_idx";
ALTER INDEX "faq_categories_deletedAt_idx" RENAME TO "faq_categories_deleted_at_idx";
ALTER INDEX "faq_categories_isActive_order_idx" RENAME TO "faq_categories_is_active_order_idx";
ALTER INDEX "faq_items_categoryId_isPublished_order_idx" RENAME TO "faq_items_category_id_is_published_order_idx";
ALTER INDEX "faq_items_categoryId_order_idx" RENAME TO "faq_items_category_id_order_idx";
ALTER INDEX "faq_items_deletedAt_idx" RENAME TO "faq_items_deleted_at_idx";
ALTER INDEX "faq_items_isPublished_idx" RENAME TO "faq_items_is_published_idx";
ALTER INDEX "faq_items_updatedAt_idx" RENAME TO "faq_items_updated_at_idx";
ALTER INDEX "faq_items_viewCount_idx" RENAME TO "faq_items_view_count_idx";
ALTER INDEX "instagram_posts_postId_key" RENAME TO "instagram_posts_post_id_key";
ALTER INDEX "media_isActive_createdAt_idx" RENAME TO "media_is_active_created_at_idx";
ALTER INDEX "media_mimeType_idx" RENAME TO "media_mime_type_idx";
ALTER INDEX "media_uploadedBy_idx" RENAME TO "media_uploaded_by_idx";
ALTER INDEX "navigation_items_parentId_idx" RENAME TO "navigation_items_parent_id_idx";
ALTER INDEX "news_createdAt_idx" RENAME TO "news_created_at_idx";
ALTER INDEX "news_isPublished_publishedAt_idx" RENAME TO "news_is_published_published_at_idx";
ALTER INDEX "pages_isPublished_isActive_idx" RENAME TO "pages_is_published_is_active_idx";
ALTER INDEX "pages_isSystemPage_idx" RENAME TO "pages_is_system_page_idx";
ALTER INDEX "post_tag_on_posts_tagId_idx" RENAME TO "post_tag_on_posts_tag_id_idx";
ALTER INDEX "posts_authorId_idx" RENAME TO "posts_author_id_idx";
ALTER INDEX "posts_categoryId_status_publishedAt_idx" RENAME TO "posts_category_id_status_published_at_idx";
ALTER INDEX "posts_deletedAt_idx" RENAME TO "posts_deleted_at_idx";
ALTER INDEX "posts_status_publishedAt_idx" RENAME TO "posts_status_published_at_idx";
ALTER INDEX "posts_status_viewCount_idx" RENAME TO "posts_status_view_count_idx";
ALTER INDEX "posts_viewCount_idx" RENAME TO "posts_view_count_idx";
ALTER INDEX "sections_pageId_order_isActive_idx" RENAME TO "sections_page_id_order_is_active_idx";

COMMIT;
