/**
 * Preview Pane
 *
 * @description エディタコンテンツのプレビューUI
 *
 * NOTE: dangerouslySetInnerHTML は安全。HTMLはLexicalの$generateHtmlFromNodes()から
 * 生成されたもので、ユーザー入力を直接含まない。Lexicalがノードツリーから
 * 安全にHTMLを構築している。
 */

'use client'

import { useEffect, useState } from 'react'
import { useLexicalComposerContext } from '@lexical/react/LexicalComposerContext'
import { $generateHtmlFromNodes } from '@lexical/html'
import { Eye, EyeOff } from 'lucide-react'
import { Button } from '@/admin/components/ui/button'

// =============================================================================
// Component
// =============================================================================

export function PreviewPane() {
  const [editor] = useLexicalComposerContext()
  const [isOpen, setIsOpen] = useState(false)
  const [html, setHtml] = useState('')

  useEffect(() => {
    if (!isOpen) return

    const update = () => {
      editor.getEditorState().read(() => {
        setHtml($generateHtmlFromNodes(editor, null))
      })
    }

    update()

    return editor.registerUpdateListener(() => {
      update()
    })
  }, [editor, isOpen])

  return (
    <div className="flex flex-col">
      <div className="shrink-0 flex items-center gap-2 border-b border-border px-3 py-1.5">
        <Button
          type="button"
          variant="ghost"
          size="sm"
          className="h-7 gap-1.5 text-xs"
          onClick={() => setIsOpen(!isOpen)}
        >
          {isOpen ? <EyeOff className="h-3.5 w-3.5" /> : <Eye className="h-3.5 w-3.5" />}
          <span>{isOpen ? 'プレビューを閉じる' : 'プレビュー'}</span>
        </Button>
      </div>

      {isOpen && (
        <div className="flex-1 overflow-y-auto border-t border-border bg-background p-4">
          {/* Safe: HTML is generated by Lexical's $generateHtmlFromNodes from the node tree */}
          {/* eslint-disable @eslint-react/dom/no-dangerously-set-innerhtml -- Lexical-generated HTML, not user input */}
          <div
            className="prose prose-sm max-w-none"
            dangerouslySetInnerHTML={{ __html: html }}
          />
          {/* eslint-enable @eslint-react/dom/no-dangerously-set-innerhtml */}
        </div>
      )}
    </div>
  )
}
