-- squawk-ignore-file renaming-column
--
-- スペース・拠点・スマートロックまわりの物理列名を snake_case へ寄せる。
--
-- 免除の根拠・自動生成を使わない理由・3 段構成は 20260804110000（認証と顧客）と同じ。
-- CHECK / index / FK の式は attnum 参照なので自動追随するが名前は残るので、
-- 列名を抱えた CHECK 5 本を明示的に改名する。

BEGIN;

-- 1. 列
ALTER TABLE spaces RENAME COLUMN "descriptionJson" TO description_json;
ALTER TABLE spaces RENAME COLUMN "descriptionHtml" TO description_html;
ALTER TABLE spaces RENAME COLUMN "descriptionPlainText" TO description_plain_text;
ALTER TABLE spaces RENAME COLUMN "addressDetail" TO address_detail;
ALTER TABLE spaces RENAME COLUMN "hourlyPrice" TO hourly_price;
ALTER TABLE spaces RENAME COLUMN "mainImageUrl" TO main_image_url;
ALTER TABLE spaces RENAME COLUMN "businessHours" TO business_hours;
ALTER TABLE spaces RENAME COLUMN "isPublished" TO is_published;
ALTER TABLE spaces RENAME COLUMN "publishedAt" TO published_at;
ALTER TABLE spaces RENAME COLUMN "isActive" TO is_active;
ALTER TABLE spaces RENAME COLUMN "reviewsEnabled" TO reviews_enabled;
ALTER TABLE spaces RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE spaces RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE spaces RENAME COLUMN "metaDescription" TO meta_description;
ALTER TABLE spaces RENAME COLUMN "metaKeywords" TO meta_keywords;
ALTER TABLE spaces RENAME COLUMN "ogpTitle" TO ogp_title;
ALTER TABLE spaces RENAME COLUMN "ogpDescription" TO ogp_description;
ALTER TABLE spaces RENAME COLUMN "ogpImageUrl" TO ogp_image_url;
ALTER TABLE spaces RENAME COLUMN "discountType" TO discount_type;
ALTER TABLE spaces RENAME COLUMN "discountValue" TO discount_value;
ALTER TABLE spaces RENAME COLUMN "durationDiscountOverride" TO duration_discount_override;
ALTER TABLE spaces RENAME COLUMN "taxRateType" TO tax_rate_type;
ALTER TABLE spaces RENAME COLUMN "locationId" TO location_id;
ALTER TABLE spaces RENAME COLUMN "categoryId" TO category_id;
ALTER TABLE spaces RENAME COLUMN "smartLockDeviceId" TO smart_lock_device_id;
ALTER TABLE space_categories RENAME COLUMN "sortOrder" TO sort_order;
ALTER TABLE space_categories RENAME COLUMN "isActive" TO is_active;
ALTER TABLE space_categories RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE space_categories RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE space_rate_plans RENAME COLUMN "spaceId" TO space_id;
ALTER TABLE space_rate_plans RENAME COLUMN "hourlyPrice" TO hourly_price;
ALTER TABLE space_rate_plans RENAME COLUMN "daysOfWeek" TO days_of_week;
ALTER TABLE space_rate_plans RENAME COLUMN "holidayMode" TO holiday_mode;
ALTER TABLE space_rate_plans RENAME COLUMN "startTime" TO start_time;
ALTER TABLE space_rate_plans RENAME COLUMN "endTime" TO end_time;
ALTER TABLE space_rate_plans RENAME COLUMN "effectiveFrom" TO effective_from;
ALTER TABLE space_rate_plans RENAME COLUMN "effectiveTo" TO effective_to;
ALTER TABLE space_rate_plans RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE space_rate_plans RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE space_reviews RENAME COLUMN "spaceId" TO space_id;
ALTER TABLE space_reviews RENAME COLUMN "customerId" TO customer_id;
ALTER TABLE space_reviews RENAME COLUMN "reservationId" TO reservation_id;
ALTER TABLE space_reviews RENAME COLUMN "isPublished" TO is_published;
ALTER TABLE space_reviews RENAME COLUMN "replyBody" TO reply_body;
ALTER TABLE space_reviews RENAME COLUMN "repliedAt" TO replied_at;
ALTER TABLE space_reviews RENAME COLUMN "repliedById" TO replied_by_id;
ALTER TABLE space_reviews RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE space_reviews RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE locations RENAME COLUMN "postalCode" TO postal_code;
ALTER TABLE locations RENAME COLUMN "streetAddress" TO street_address;
ALTER TABLE locations RENAME COLUMN "buildingName" TO building_name;
ALTER TABLE locations RENAME COLUMN "accessLines" TO access_lines;
ALTER TABLE locations RENAME COLUMN "parkingInfo" TO parking_info;
ALTER TABLE locations RENAME COLUMN "imageUrl" TO image_url;
ALTER TABLE locations RENAME COLUMN "imageUrls" TO image_urls;
ALTER TABLE locations RENAME COLUMN "businessHours" TO business_hours;
ALTER TABLE locations RENAME COLUMN "specialHolidays" TO special_holidays;
ALTER TABLE locations RENAME COLUMN "googleBusinessPlaceId" TO google_business_place_id;
ALTER TABLE locations RENAME COLUMN "googleReviewUrl" TO google_review_url;
ALTER TABLE locations RENAME COLUMN "priceRange" TO price_range;
ALTER TABLE locations RENAME COLUMN "paymentAccepted" TO payment_accepted;
ALTER TABLE locations RENAME COLUMN "phoneNumber" TO phone_number;
ALTER TABLE locations RENAME COLUMN "gbpSyncEnabled" TO gbp_sync_enabled;
ALTER TABLE locations RENAME COLUMN "gbpSyncedAt" TO gbp_synced_at;
ALTER TABLE locations RENAME COLUMN "gbpSyncError" TO gbp_sync_error;
ALTER TABLE locations RENAME COLUMN "sortOrder" TO sort_order;
ALTER TABLE locations RENAME COLUMN "isPublished" TO is_published;
ALTER TABLE locations RENAME COLUMN "isActive" TO is_active;
ALTER TABLE locations RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE locations RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE locations RENAME COLUMN "defaultSmartLockDeviceId" TO default_smart_lock_device_id;
ALTER TABLE blocked_dates RENAME COLUMN "spaceId" TO space_id;
ALTER TABLE blocked_dates RENAME COLUMN "locationId" TO location_id;
ALTER TABLE blocked_dates RENAME COLUMN "startDate" TO start_date;
ALTER TABLE blocked_dates RENAME COLUMN "endDate" TO end_date;
ALTER TABLE blocked_dates RENAME COLUMN "createdBy" TO created_by;
ALTER TABLE blocked_dates RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE blocked_dates RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE block_templates RENAME COLUMN "nodeJson" TO node_json;
ALTER TABLE block_templates RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE block_templates RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE block_templates RENAME COLUMN "createdBy" TO created_by;
ALTER TABLE smart_lock_devices RENAME COLUMN "locationId" TO location_id;
ALTER TABLE smart_lock_devices RENAME COLUMN "deviceId" TO device_id;
ALTER TABLE smart_lock_devices RENAME COLUMN "deviceName" TO device_name;
ALTER TABLE smart_lock_devices RENAME COLUMN "deviceType" TO device_type;
ALTER TABLE smart_lock_devices RENAME COLUMN "isActive" TO is_active;
ALTER TABLE smart_lock_devices RENAME COLUMN "pairedLockDeviceId" TO paired_lock_device_id;
ALTER TABLE smart_lock_devices RENAME COLUMN "lastLockState" TO last_lock_state;
ALTER TABLE smart_lock_devices RENAME COLUMN "lastDoorState" TO last_door_state;
ALTER TABLE smart_lock_devices RENAME COLUMN "lastBattery" TO last_battery;
ALTER TABLE smart_lock_devices RENAME COLUMN "lastStateAt" TO last_state_at;
ALTER TABLE smart_lock_devices RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE smart_lock_devices RENAME COLUMN "updatedAt" TO updated_at;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "reservationId" TO reservation_id;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "deviceId" TO device_id;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "passcodeCiphertext" TO passcode_ciphertext;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "switchbotCommandId" TO switchbot_command_id;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "switchbotDeleteCommandId" TO switchbot_delete_command_id;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "switchbotKeyId" TO switchbot_key_id;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "startTime" TO start_time;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "endTime" TO end_time;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "failureReason" TO failure_reason;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "confirmedAt" TO confirmed_at;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "revokeRequestedAt" TO revoke_requested_at;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "revokedAt" TO revoked_at;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "createdAt" TO created_at;
ALTER TABLE smart_lock_passcodes RENAME COLUMN "updatedAt" TO updated_at;

-- 2. Prisma 管理オブジェクト（FK / index）
ALTER TABLE "block_templates" RENAME CONSTRAINT "block_templates_createdBy_fkey" TO "block_templates_created_by_fkey";
ALTER TABLE "blocked_dates" RENAME CONSTRAINT "blocked_dates_createdBy_fkey" TO "blocked_dates_created_by_fkey";
ALTER TABLE "blocked_dates" RENAME CONSTRAINT "blocked_dates_locationId_fkey" TO "blocked_dates_location_id_fkey";
ALTER TABLE "blocked_dates" RENAME CONSTRAINT "blocked_dates_spaceId_fkey" TO "blocked_dates_space_id_fkey";
ALTER TABLE "locations" RENAME CONSTRAINT "locations_defaultSmartLockDeviceId_fkey" TO "locations_default_smart_lock_device_id_fkey";
ALTER TABLE "smart_lock_devices" RENAME CONSTRAINT "smart_lock_devices_locationId_fkey" TO "smart_lock_devices_location_id_fkey";
ALTER TABLE "smart_lock_devices" RENAME CONSTRAINT "smart_lock_devices_pairedLockDeviceId_fkey" TO "smart_lock_devices_paired_lock_device_id_fkey";
ALTER TABLE "smart_lock_passcodes" RENAME CONSTRAINT "smart_lock_passcodes_deviceId_fkey" TO "smart_lock_passcodes_device_id_fkey";
ALTER TABLE "smart_lock_passcodes" RENAME CONSTRAINT "smart_lock_passcodes_reservationId_fkey" TO "smart_lock_passcodes_reservation_id_fkey";
ALTER TABLE "space_rate_plans" RENAME CONSTRAINT "space_rate_plans_spaceId_fkey" TO "space_rate_plans_space_id_fkey";
ALTER TABLE "space_reviews" RENAME CONSTRAINT "space_reviews_customerId_fkey" TO "space_reviews_customer_id_fkey";
ALTER TABLE "space_reviews" RENAME CONSTRAINT "space_reviews_repliedById_fkey" TO "space_reviews_replied_by_id_fkey";
ALTER TABLE "space_reviews" RENAME CONSTRAINT "space_reviews_reservationId_fkey" TO "space_reviews_reservation_id_fkey";
ALTER TABLE "space_reviews" RENAME CONSTRAINT "space_reviews_spaceId_fkey" TO "space_reviews_space_id_fkey";
ALTER TABLE "spaces" RENAME CONSTRAINT "spaces_categoryId_fkey" TO "spaces_category_id_fkey";
ALTER TABLE "spaces" RENAME CONSTRAINT "spaces_locationId_fkey" TO "spaces_location_id_fkey";
ALTER TABLE "spaces" RENAME CONSTRAINT "spaces_smartLockDeviceId_fkey" TO "spaces_smart_lock_device_id_fkey";
ALTER INDEX "block_templates_createdAt_idx" RENAME TO "block_templates_created_at_idx";
ALTER INDEX "block_templates_createdBy_idx" RENAME TO "block_templates_created_by_idx";
ALTER INDEX "blocked_dates_createdBy_idx" RENAME TO "blocked_dates_created_by_idx";
ALTER INDEX "blocked_dates_locationId_startDate_endDate_idx" RENAME TO "blocked_dates_location_id_start_date_end_date_idx";
ALTER INDEX "blocked_dates_scope_startDate_endDate_idx" RENAME TO "blocked_dates_scope_start_date_end_date_idx";
ALTER INDEX "blocked_dates_spaceId_startDate_endDate_idx" RENAME TO "blocked_dates_space_id_start_date_end_date_idx";
ALTER INDEX "locations_defaultSmartLockDeviceId_idx" RENAME TO "locations_default_smart_lock_device_id_idx";
ALTER INDEX "locations_gbpSyncError_idx" RENAME TO "locations_gbp_sync_error_idx";
ALTER INDEX "locations_isPublished_isActive_idx" RENAME TO "locations_is_published_is_active_idx";
ALTER INDEX "locations_sortOrder_idx" RENAME TO "locations_sort_order_idx";
ALTER INDEX "smart_lock_devices_deviceId_key" RENAME TO "smart_lock_devices_device_id_key";
ALTER INDEX "smart_lock_devices_locationId_idx" RENAME TO "smart_lock_devices_location_id_idx";
ALTER INDEX "smart_lock_passcodes_deviceId_idx" RENAME TO "smart_lock_passcodes_device_id_idx";
ALTER INDEX "smart_lock_passcodes_reservationId_deviceId_key" RENAME TO "smart_lock_passcodes_reservation_id_device_id_key";
ALTER INDEX "smart_lock_passcodes_status_endTime_idx" RENAME TO "smart_lock_passcodes_status_end_time_idx";
ALTER INDEX "smart_lock_passcodes_status_revokeRequestedAt_idx" RENAME TO "smart_lock_passcodes_status_revoke_requested_at_idx";
ALTER INDEX "space_rate_plans_spaceId_updatedAt_idx" RENAME TO "space_rate_plans_space_id_updated_at_idx";
ALTER INDEX "space_reviews_customerId_idx" RENAME TO "space_reviews_customer_id_idx";
ALTER INDEX "space_reviews_repliedById_idx" RENAME TO "space_reviews_replied_by_id_idx";
ALTER INDEX "space_reviews_reservationId_key" RENAME TO "space_reviews_reservation_id_key";
ALTER INDEX "space_reviews_spaceId_isPublished_createdAt_idx" RENAME TO "space_reviews_space_id_is_published_created_at_idx";
ALTER INDEX "spaces_addressDetail_idx" RENAME TO "spaces_address_detail_idx";
ALTER INDEX "spaces_categoryId_idx" RENAME TO "spaces_category_id_idx";
ALTER INDEX "spaces_isPublished_isActive_idx" RENAME TO "spaces_is_published_is_active_idx";
ALTER INDEX "spaces_locationId_idx" RENAME TO "spaces_location_id_idx";
ALTER INDEX "spaces_publishedAt_isActive_idx" RENAME TO "spaces_published_at_is_active_idx";
ALTER INDEX "spaces_smartLockDeviceId_idx" RENAME TO "spaces_smart_lock_device_id_idx";

-- 3. 手書き CHECK の名前
ALTER TABLE locations RENAME CONSTRAINT "locations_accessLines_array_check" TO "locations_access_lines_array_check";
ALTER TABLE locations RENAME CONSTRAINT "locations_imageUrls_array_check" TO "locations_image_urls_array_check";
ALTER TABLE space_rate_plans RENAME CONSTRAINT "space_rate_plans_endTime_format_check" TO "space_rate_plans_end_time_format_check";
ALTER TABLE space_rate_plans RENAME CONSTRAINT "space_rate_plans_hourlyPrice_non_negative_check" TO "space_rate_plans_hourly_price_non_negative_check";
ALTER TABLE space_rate_plans RENAME CONSTRAINT "space_rate_plans_startTime_format_check" TO "space_rate_plans_start_time_format_check";

COMMIT;
