-- RESEND-AUDIT M7: preserve suppression state across Customer anonymize/merge.
--
-- 目的: `anonymizeCustomerCommand` は emailCanonical を
-- `deleted+<id>@anonymized.local` に置換するが `emailDeliveryStatus`
-- (HARD_BOUNCED / COMPLAINED) は残す。従来 `getSuppressedEmailSet` は
-- 匿名化後の placeholder を hash してしまい、実 email の suppression が
-- silent に失われていた (再登録した同 email に送信して sender reputation を
-- 悪化させる原因)。同様に `mergeCustomerCommand` の source 側 suppression も
-- 削除時点で失われていた。
--
-- 修正: `suppressedEmailHash` (nullable) を追加する。anonymize / merge で
-- emailCanonical を書き換える前に、被抑制状態 (HARD_BOUNCED / COMPLAINED)
-- だった emailCanonical の `hashSuppressedEmailCandidate` 値を保存する。
-- `getSuppressedEmailSet` は「emailDeliveryStatus ∈ 抑制」経路と
-- 「suppressedEmailHash IS NOT NULL」経路の union を返す。
--
-- 破壊的変更: なし (全 nullable のため既存行は影響なし)。
-- 現行データセットは小規模のため index は張らない (full scan で十分)。

-- AlterTable
ALTER TABLE "customers" ADD COLUMN     "suppressedEmailHash" VARCHAR(128);
